// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.Constants.OIConstants;
import frc.robot.subsystems.DriveSubsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.LiftSubsystem;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class DriveCommand extends CommandBase {

    //private Joystick m_joystickDriver;
    private double m_Speed;
    private double m_Distance;
    private int count;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private final DriveSubsystem m_robotDrive;
    private final LiftSubsystem m_LiftSubsystem;
    private final XboxController m_driverController;
    private final XboxController m_manipulatorController;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


    public DriveCommand(DriveSubsystem subsystem, LiftSubsystem liftsub, 
     XboxController dController, XboxController mController) {

     
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_robotDrive = subsystem;
        m_LiftSubsystem = liftsub;
        addRequirements(m_robotDrive);
        addRequirements(m_LiftSubsystem);
        m_driverController = dController;
        m_manipulatorController = mController;
       // addRequirements(m_driverController);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        
        //m_joystickDriver = new Joystick(0);
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
      SmartDashboard.putString("DriveCommand", "In init");
      count = 0;
    }



    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        count++;
        SmartDashboard.putNumber("count", count);
        SmartDashboard.putNumber("getLeftX", m_driverController.getLeftX());
        
        m_robotDrive.drive(
            -MathUtil.applyDeadband(m_driverController.getLeftY(), OIConstants.kDriveDeadband),
            -MathUtil.applyDeadband(m_driverController.getLeftX(), OIConstants.kDriveDeadband),
            -MathUtil.applyDeadband(m_driverController.getRightX(), OIConstants.kDriveDeadband),
            true, false);
        m_robotDrive.periodic(); 

        m_LiftSubsystem.liftDrive(
                m_manipulatorController.getLeftY(), 
                0,//m_manipulatorController.getPOV(LiftConstants.kPOIRotationDOWN), 
                0,//m_manipulatorController.getPOV(LiftConstants.kPOIRotationUP), 
                m_manipulatorController.getYButton(),
                m_manipulatorController.getBButton(),
                m_manipulatorController.getAButton());
        
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {

          return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
